name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Build Everything
      run: |
        npm install
        make clean
        make all
